### PR TITLE
increase timeout for pkexec in login_service

### PR DESCRIPTION
**Pull request by offlinehacker**
increase timeout for pkexec from 8 to 30 seconds if password is asked via polkit-auth-agent

### CODE REVIEW

**Comment by calexandru2018** [comment]
Hi @offlinehacker :)

Thanks for the PR, though I was wondering why changing it to 30 seconds ? It seems unnecessary long since the only thing that the code does is writing the data to the file, which usually does not take more then 4 seconds.

**Comment by offlinehacker** [comment]
The issue is that it uses pkexec, and pkexec uses polkit. In my case invoking pkexec asks me for password (using gnome-polkit-auth-agent), which is expected behavior I want to have, as for security reasons I don't want pkexec without password. If user does not enter password before timeout there is an error.

**Comment by calexandru2018** [comment]
>  In my case invoking pkexec asks me for password (using gnome-polkit-auth-agent), which is expected behavior I want to have, as for security reasons I don't want pkexec without password.

That's exactly why PolKit support was added. I think that 30 seconds is rather long and users might mistake this by a random crash since the GUI will be unresponsive during those 30 seconds. I would agree if maybe it would be increased to 15, but 30 IMO seems to be too much.

**Comment by offlinehacker** [comment]
I get the following dialog when connecting. While `15s` seems ok, `8s` is too short i think. The issue is maybe is you have have long password, and maybe `15s` is not enough, since you have to select user first. But i agree `15s` is enough for most users, but i am wondering if there is any better solution?

polkit_pass

**Comment by calexandru2018** [comment]
> The issue is maybe is you have have long password,

Regarding this, you can copy the password before you "activate" PolKit, not optimal I know, but it's quicker that way.

> but i am wondering if there is any better solution?

I do agree nonetheless that is not optimal, and alternative ways are being looked into.

**Review by calexandru2018 — APPROVED** [review]

**Pull request merged**
